name: responsive_scaffold_nullsafe
description: On mobile it shows a list and pushes to details and on tablet it shows the List and the selected item.
version: 1.0.1
homepage: https://github.com/vanshg395/responsive_scaffold_nullsafe

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  scroll_to_index: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.5.3

flutter:
